### ISSUE TITLE
reference to flake8 TYP warnings in hypermodern-python chapter 4

### ISSUE THREAD

**Issue by oncleben31** [cjolowicz/blog#11]
In [chapter four](https://cjolowicz.github.io/posts/hypermodern-python-04-typing/#adding-type-annotations-to-nox-sessions)
There is a reference to `TYP` warnings. In the section before we have set `ANN` warnings. It's inconsistent and seems related to an old way of implementing `flake8-annotations`

By the way due to this I had difficulties to understand what mean: 

> If you disabled type coverage warnings (TYP) for Nox sessions, re-enable them for the purposes of this section.

It could be interesting to explain that is related to the `per-file-ignores` parameter

**Comment by cjolowicz** [comment]
Thank you for finding and reporting this!

ad443c68884f83040555392a269c6947e70d87e7
